# This action will run every day at 5:00am EST
# If an issue has had no activity (comments) in 90-days, it will add the tag 'stale' and and comment to notify of the status.
# If an issue that has been marked stale is inactive for an additional 90-days, it will close the issue.

# Note: You must set the GitHub Repository Secret GITHUB_TOKEN_STALE to a Personal Access Token (PAT) that allows the stale workflow to authenticate and perform API calls to GitHub.

# Ref: https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues

name: Tag Stale and Close Inactive
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 90
          days-before-issue-close: 90
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 90 days with no activity. Remove stale label or comment or this will be closed in 90 days."
          close-issue-message: "This issue was closed because it has been inactive for 90 days since being marked as stale."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.STALE_PAT }}
